### PR TITLE
Remove stale environment variables

### PR DESCRIPTION
**Pull request by loafoe**
- Uses v3 PATCH call to remove environment variables

### CODE REVIEW

**Comment by loafoe** [comment]
@ArthurHlt the BitsManager is probably not the canonical place to add this call but I have no idea how to change the V3 client.

**Comment by ArthurHlt** [comment]
Thanks @loafoe, you help a lot.
 I understand why doing this but It will need some test about it too if you can do them also ?

**Comment by loafoe** [comment]
I will add some test

**Comment by loafoe** [comment]
@ArthurHlt isolation segments are disabled for all CF deployments I have access to so running test will always throw this:

```shell
Creating isolation segment segment-acc-tf ...
panic: You are not authorized to perform the requested action
```

Any suggestion on how to run such tests?

**Comment by ArthurHlt** [comment]
@loafoe you can just comment this part: https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/c8a7f68962e1d5fa3629e2c95745cd0aaab00f1e/cloudfoundry/provider_test.go#L571-L594 (do not forget to uncomment after) and after just run the test(s) you are interested with `TF_ACC=1 go test -v -run 'regex-of-test-name' -timeout 120m ./...` (example for `regex-of-test-name` => `TestAccUser_WithGroups_normal`)

**Comment by loafoe** [comment]
@ArthurHlt updated existing tests to validate the new code paths. Running `TestAccResApp_app1` standalone worked fine (thanks for merging the isolation segment stuff!!)

**Comment by ArthurHlt** [comment]
cool for the tests thanks, did you see my comments on the PR ?

**Comment by loafoe** [comment]
@ArthurHlt sorry might have missed PR comment, are you referring to specific section?

**Pull request merged**
