### PR TITLE
Accept DOWN state during staging/deploy. Fixes #317

### LINKED ISSUE #317: Deploy sometimes fail with: Instance 0 failed with state DOWN for app ${app_name}
Sometimes app deployments randomly fail with the following error:

`Instance 0 failed with state DOWN for app ${app_name}`

It's hard to debug as the app is removed shortly after. Suspecting a race condition in the RunBinder state checking logic.

https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/c2f2cf608d7f9135f710e5e8ed116f7ed6ca9161/cloudfoundry/managers/appdeployers/runbinder.go#L138-L146

### PR DESCRIPTION
**Pull request by loafoe**

### CODE REVIEW

**Comment by ArthurHlt** [comment]
thanks @loafoe for the catch
Here it's like you are accepting error on some instances. Maybe I miss the point to allow DOWN instance here ?

Logs from recent logs from app did  not provide you information to not what happens to this particular instance ?

**Comment by loafoe** [comment]
@ArthurHlt correct, this happens completely random. Also, the app comes up successfully, but by that time Terraform has already failed. 

I suspect that CF stages the app and then brings it down right before deploying a new instance. If the provider happens to check the state of the application at exactly that moment it will see `DOWN` state and then assume the app has failed.. even though the app is still in process of being deployed.

**Comment by ArthurHlt** [comment]
So i have understood your problem I will more implement a retry that simply wipe it. I'm closing it and implement this right in the minute

**Comment by loafoe** [comment]
thanks @ArthurHlt !

**Pull request closed without merging**
