### PR TITLE
Increase service instance timeouts to 20 minutes

### PR DESCRIPTION
**Pull request by mogul**
[Broker an AWS EKS instance](https://github.com/GSA/eks-brokerpak) takes longer than 15 minutes, so the Terraform provider assumes that provisioning has failed, even though provisioning continues and succeeds a few minutes later. 

In lieu of making this parameter configurable (I'm not very familiar with Go), I'm offering this PR increasing the timeout as the simplest possible way to solve my problem and move on. (I can also look at making this value configurable, but that's beyond my meager Go skills today.)

Also updates the documentation.

### CODE REVIEW

**Comment by ArthurHlt** [comment]
Thanks for the PR but i don't think you need it, normally using Timeout block allow you to set timeout inside your tf file as described here: https://www.terraform.io/docs/language/resources/syntax.html#operation-timeouts 

Maybe PR will be more on documentation to clarify that

**Comment by mogul** [comment]
I thought that too, but doesn't the provider have to explicitly provide timeouts for a given resource? From that page, emphasis mine:

> **Some** resource types provide a special timeouts nested block argument that allows you to customize how long certain operations are allowed to take before being considered to have failed. For example, aws_db_instance allows configurable timeouts for create, update and delete operations.
> 
> **Timeouts are handled entirely by the resource type implementation in the provider**, but resource types offering these features follow the convention of defining a child block called timeouts that has a nested argument named after each operation that has a configurable timeout value. Each of these arguments takes a string representation of a duration, such as "60m" for 60 minutes, "10s" for ten seconds, or "2h" for two hours.
> [...]
> **The set of configurable operations is chosen by each resource type. Most resource types do not support the timeouts block at all. Consult the documentation for each resource type to see which operations it offers for configuration, if any.**

In `resource_service_instance` [the timeouts appear to have hardcoded values](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/8a6fe492c6b69752d44a91ac15f940e50d822f23/cloudfoundry/resource_cf_service_instance.go#L31-L35). 

By comparison, in `resource_app` [the timeout is explicitly exposed and configurable](https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/blob/c2f2cf608d7f9135f710e5e8ed116f7ed6ca9161/cloudfoundry/resource_cf_app.go#L97-L100).

Don't get me wrong, I'm happy to find out that it's configurable-but-not-documented for service instances if that's the case, but I'm not seeing that in the code!

**Comment by ArthurHlt** [comment]
Those are 2 differents timeout, one is for controlling terraform timeout for resource and the other one on app is actually a param to send for cloud foundry app creation/update api verb.

I'm actually like 99% this should works but as I didn't really tried and I don't remember when I did that and why it's not 100%.

But as you might find on aws provider doc, you can find timeout on their doc here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/db_instance#timeouts but have the exact same resource definition we have here: https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/resource_aws_db_instance.go as you can see no timeouts param in schema but Timeouts struct in resource.

Let me know if it not works it will be helpful if you can test this, I could update documentation after you have tested successfully

**Comment by mogul** [comment]
Confirmed: Timeouts are supported!

**Pull request closed without merging**
