### PR TITLE
Workaround when fail catalog when not accessible stuck state

### PR DESCRIPTION
**Pull request by ArthurHlt**
Context is in issue #329 

This add to provider configuration a new variable called `force_broker_not_fail_when_catalog_not_accessible` associated to env var `CF_FORCE_BROKER_NOT_FAIL_CATALOG` when this variable is set to `true` it enforces `fail_when_catalog_not_accessible` to be `false` and every broker.

Example of usage:

1. create a broker:
```hcl
provider "cloudfoundry" {
# creds
}

resource "cloudfoundry_service_broker" "bookstore" {
  name                             = "bookstore"
  url                                  = "https://bookstore-service-broker.domain.net"
  username                      = "admin"
  password                       = "supersecret"
  fail_when_catalog_not_accessible = false
}
```
2. run `terraform apply` to create broker
3. Make your broker unaccessible
4. When running `terraform apply` you are now stuck due to fail
5. Simply now run command `CF_FORCE_BROKER_NOT_FAIL_CATALOG=true terraform apply` and this will not check for catalog and unstuck you

### CODE REVIEW

**Comment by mogul** [comment]
This change causes generation of an accurate plan, but Terraform still errors out when actually performing the `apply` because it's still checking the catalog:

```
% CF_FORCE_BROKER_NOT_FAIL_CATALOG=true terraform apply -var-file=terraform.production.tfvars           

Warning: Provider development overrides are in effect

The following provider development overrides are set in the CLI configuration:
 - cloudfoundry-community/cloudfoundry in /Users/bretamogilefsky/go/src/github.com/terraform-providers/terraform-provider-cloudfoundry

The behavior may therefore not match any released version of the provider and
applying changes may cause the state to become incompatible with published
releases.

module.broker_solr.random_uuid.client_username: Refreshing state... [id=63d2d47d-f315-c647-31fd-9d60600fee89]
module.broker_solr.random_password.client_password: Refreshing state... [id=none]
module.broker_solr.cloudfoundry_route.ssb_uri: Refreshing state... [id=178725bd-3eda-4a84-abd6-a848305978d5]
module.broker_solr.cloudfoundry_service_instance.db: Refreshing state... [id=3c73e801-d72e-4c60-aec7-26a29edab9dc]
aws_route53_zone.zone[0]: Refreshing state... [id=Z07355901NXGEZPEJONPN]
module.broker_aws.random_password.client_password: Refreshing state... [id=none]
module.broker_aws.random_uuid.client_username: Refreshing state... [id=ff97952a-f446-ffd7-9c1a-f2d283bf53d8]
module.broker_eks.random_password.client_password: Refreshing state... [id=none]
module.broker_eks.random_uuid.client_username: Refreshing state... [id=15414ad1-23d6-4126-a053-11a38e2c9d0a]
module.broker_eks.cloudfoundry_route.ssb_uri: Refreshing state... [id=47d6d9c4-3b7e-49b3-85f4-c728dc1b8a9e]
module.broker_aws.cloudfoundry_route.ssb_uri: Refreshing state... [id=c8f4d632-cb0e-4003-b247-b128ef566145]
module.broker_aws.cloudfoundry_service_instance.db: Refreshing state... [id=977a240a-080b-42ab-bc39-459231ac4449]
module.broker_eks.cloudfoundry_service_instance.db: Refreshing state... [id=aca65a42-0575-44a5-87f9-67eed619de57]
module.broker_aws.cloudfoundry_app.ssb: Refreshing state... [id=94a5465e-97e6-469b-a0d6-4a2f4a8458fb]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"]: Refreshing state... [id=7f1fc84c-443e-4916-8dfc-3a2910ee0e85]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"]: Refreshing state... [id=11fb451e-f641-4154-96da-1c3278ad50ef]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"]: Refreshing state... [id=2ac8385d-b036-4e10-87b8-ea5542725a41]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"]: Refreshing state... [id=8d972a54-83d3-4321-b660-f0e1f3f25c31]
module.broker_eks.cloudfoundry_app.ssb: Refreshing state... [id=05a35f5d-86d7-4dc4-aa01-a81f3caa12e4]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"]: Refreshing state... [id=585c8e2d-e0bc-4570-9ee4-c82ab24a0072]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"]: Refreshing state... [id=7fa36384-ca62-4391-976d-124a18ce62c1]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"]: Refreshing state... [id=9ac69fe2-ae11-48a5-97b4-a2012bc84794]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"]: Refreshing state... [id=5ae76e42-fee9-4947-ae60-763f573fb857]
cloudfoundry_service_instance.k8s_cluster: Refreshing state... [id=0f63f2ee-c912-4430-8896-1815c0428d84]
module.broker_solr.cloudfoundry_app.ssb: Refreshing state... [id=ab966f04-be8e-47f3-bef1-994389f68ed8]
module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"]: Refreshing state... [id=67eb0afc-14d2-4654-9ccb-92159ea9b891]
module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"]: Refreshing state... [id=ac2a990e-b945-474a-8441-8b1fe4cd29af]
module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"]: Refreshing state... [id=a5a2e4e5-c51c-4606-9326-459afbadbe13]
module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"]: Refreshing state... [id=277bacda-14cd-41ac-8938-de9abc066671]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # cloudfoundry_service_instance.k8s_cluster will be updated in-place
  ~ resource "cloudfoundry_service_instance" "k8s_cluster" {
        id                             = "0f63f2ee-c912-4430-8896-1815c0428d84"
        name                           = "ssb-k8s"
      + replace_on_params_change       = false
      + replace_on_service_plan_change = false
        tags                           = [
            "k8s",
        ]
        # (3 unchanged attributes hidden)

      ~ timeouts {
          ~ create = "30m" -> "40m"
            # (1 unchanged attribute hidden)
        }
    }

  # module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "8d972a54-83d3-4321-b660-f0e1f3f25c31"
      ~ name                             = "ssb-ssb-aws-gsa-datagov-development" -> "ssb-aws-gsa-datagov-development"
      ~ url                              = "https://ssb-intimate-mink.app.cloud.gov" -> "https://ssb-aws-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "11fb451e-f641-4154-96da-1c3278ad50ef"
      ~ name                             = "ssb-ssb-aws-gsa-datagov-management" -> "ssb-aws-gsa-datagov-management"
      ~ url                              = "https://ssb-intimate-mink.app.cloud.gov" -> "https://ssb-aws-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "7f1fc84c-443e-4916-8dfc-3a2910ee0e85"
      ~ name                             = "ssb-ssb-aws-gsa-datagov-prod" -> "ssb-aws-gsa-datagov-prod"
      ~ url                              = "https://ssb-intimate-mink.app.cloud.gov" -> "https://ssb-aws-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "2ac8385d-b036-4e10-87b8-ea5542725a41"
      ~ name                             = "ssb-ssb-aws-gsa-datagov-staging" -> "ssb-aws-gsa-datagov-staging"
      ~ url                              = "https://ssb-intimate-mink.app.cloud.gov" -> "https://ssb-aws-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "9ac69fe2-ae11-48a5-97b4-a2012bc84794"
      ~ name                             = "ssb-ssb-eks-gsa-datagov-development" -> "ssb-eks-gsa-datagov-development"
      ~ url                              = "https://ssb-smart-garfish.app.cloud.gov" -> "https://ssb-eks-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "585c8e2d-e0bc-4570-9ee4-c82ab24a0072"
      ~ name                             = "ssb-ssb-eks-gsa-datagov-management" -> "ssb-eks-gsa-datagov-management"
      ~ url                              = "https://ssb-smart-garfish.app.cloud.gov" -> "https://ssb-eks-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "5ae76e42-fee9-4947-ae60-763f573fb857"
      ~ name                             = "ssb-ssb-eks-gsa-datagov-prod" -> "ssb-eks-gsa-datagov-prod"
      ~ url                              = "https://ssb-smart-garfish.app.cloud.gov" -> "https://ssb-eks-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
        id                               = "7fa36384-ca62-4391-976d-124a18ce62c1"
      ~ name                             = "ssb-ssb-eks-gsa-datagov-staging" -> "ssb-eks-gsa-datagov-staging"
      ~ url                              = "https://ssb-smart-garfish.app.cloud.gov" -> "https://ssb-eks-gsa-datagov-management.app.cloud.gov"
        # (8 unchanged attributes hidden)
    }

  # module.broker_solr.cloudfoundry_app.ssb will be updated in-place
  ~ resource "cloudfoundry_app" "ssb" {
      ~ enable_ssh           = true -> false
      ~ environment          = (sensitive value)
        id                   = "ab966f04-be8e-47f3-bef1-994389f68ed8"
      ~ id_bg                = "ab966f04-be8e-47f3-bef1-994389f68ed8" -> (known after apply)
        name                 = "ssb-solr"
        # (15 unchanged attributes hidden)


        # (3 unchanged blocks hidden)
    }

  # module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
      ~ fail_when_catalog_not_accessible = true -> false
        id                               = "67eb0afc-14d2-4654-9ccb-92159ea9b891"
        name                             = "ssb-solr-gsa-datagov-development"
      ~ password                         = (sensitive value)
      ~ url                              = "https://ssb-improved-bunny.app.cloud.gov" -> "https://ssb-solr-gsa-datagov-management.app.cloud.gov"
        # (6 unchanged attributes hidden)
    }

  # module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
      ~ fail_when_catalog_not_accessible = true -> false
        id                               = "a5a2e4e5-c51c-4606-9326-459afbadbe13"
        name                             = "ssb-solr-gsa-datagov-management"
      ~ password                         = (sensitive value)
      ~ url                              = "https://ssb-improved-bunny.app.cloud.gov" -> "https://ssb-solr-gsa-datagov-management.app.cloud.gov"
        # (6 unchanged attributes hidden)
    }

  # module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
      ~ fail_when_catalog_not_accessible = true -> false
        id                               = "ac2a990e-b945-474a-8441-8b1fe4cd29af"
        name                             = "ssb-solr-gsa-datagov-prod"
      ~ password                         = (sensitive value)
      ~ url                              = "https://ssb-improved-bunny.app.cloud.gov" -> "https://ssb-solr-gsa-datagov-management.app.cloud.gov"
        # (6 unchanged attributes hidden)
    }

  # module.broker_solr.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"] will be updated in-place
  ~ resource "cloudfoundry_service_broker" "space_scoped_broker" {
      ~ fail_when_catalog_not_accessible = true -> false
        id                               = "277bacda-14cd-41ac-8938-de9abc066671"
        name                             = "ssb-solr-gsa-datagov-staging"
      ~ password                         = (sensitive value)
      ~ url                              = "https://ssb-improved-bunny.app.cloud.gov" -> "https://ssb-solr-gsa-datagov-management.app.cloud.gov"
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 14 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"]: Modifying... [id=2ac8385d-b036-4e10-87b8-ea5542725a41]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"]: Modifying... [id=11fb451e-f641-4154-96da-1c3278ad50ef]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"]: Modifying... [id=5ae76e42-fee9-4947-ae60-763f573fb857]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/prod"]: Modifying... [id=7f1fc84c-443e-4916-8dfc-3a2910ee0e85]
module.broker_aws.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"]: Modifying... [id=8d972a54-83d3-4321-b660-f0e1f3f25c31]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/management"]: Modifying... [id=585c8e2d-e0bc-4570-9ee4-c82ab24a0072]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/staging"]: Modifying... [id=7fa36384-ca62-4391-976d-124a18ce62c1]
module.broker_eks.cloudfoundry_service_broker.space_scoped_broker["gsa-datagov/development"]: Modifying... [id=9ac69fe2-ae11-48a5-97b4-a2012bc84794]

Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-smart-garfish.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-smart-garfish.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-intimate-mink.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-intimate-mink.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-smart-garfish.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-intimate-mink.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-intimate-mink.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {



Error: The service broker rejected the request. Status Code: 404 Not Found, Body: 404 Not Found: Requested route ('ssb-smart-garfish.app.cloud.gov') does not exist.


  on broker/main.tf line 91, in resource "cloudfoundry_service_broker" "space_scoped_broker":
  91: resource "cloudfoundry_service_broker" "space_scoped_broker" {


```

**Comment by mogul** [comment]
I grabbed the tfstate out of S3 and noticed this, not sure if it's relevant:
```
% grep fail_when ssb-tfstate 
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": false,
            "fail_when_catalog_not_accessible": true,
            "fail_when_catalog_not_accessible": true,
            "fail_when_catalog_not_accessible": true,
            "fail_when_catalog_not_accessible": true,
```

The ones where it is `true` are the 4x `module.broker_solr.cloudfoundry_service_broker.space_scoped_broker[*]`. Not sure if that matters/helps. 🤷

**Comment by mogul** [comment]
Confirmed I'm on the most recent Terraform (0.14.9) in case that makes a difference.

Also the offer still stands: I'm online in the CF Slack if you want to debug live!

**Comment by mogul** [comment]
After coordinating in Slack, we confirmed that this last commit addressed the problem. Thank you!

**Comment by ArthurHlt** [comment]
Fixed remotely with @mogul on slack. Update Request was sending wrong parameters

**Pull request merged**
