### PR TITLE
Update cf service instance test go for metadata label

### PR DESCRIPTION
**Pull request by Jess713**
This enables using Metadata label feature in Terraform 
Example)
```
resource "cf_service_instance" "my-cloud" {
  name                  = "${var.service_name}-my-cloud"
  space                 = var.cf_space_id
  service_plan      = data.cf_service.hana-cloud.service_plans["mycloud"]
  labels = {
    instance-name = "${var.service_name}-my-cloud"
    instance-type = "my-cloud"
  }
```

### CODE REVIEW

**Comment by sleungcy** [comment]
We should update the wiki page as well
https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/wiki/resource_service_instance

Also wondering if we have implementation for the annotation or just the label only?

**Comment by Jess713** [comment]
hey Sam
I only implemented for label only.
Should we do the annotation too?
I'll take a look at the wiki !

**Comment by loafoe** [comment]
@Jess713 can you check the `golint` remarks? thx!

**Comment by loafoe** [comment]
@Jess713 thanks 🚀  Can you please update documentation in `docs/resources/service_instance.md` to describe the new `labels` argument. Should be good to merge then.

**Comment by Jess713** [comment]
Hi @loafoe , I updated service_instance.md . please review. 
Thanks!

**Pull request merged**
