### PR TITLE
route data source: migrate to ccv3

### PR DESCRIPTION
**Pull request by Cocossoul**

### CODE REVIEW

**Comment by sleungcy** [comment]
I think we should switch to https://github.com/cloudfoundry/go-cfclient and get off of the fork

**Comment by Cocossoul** [comment]
@sleungcy that would be great, but in order to do that we need to migrate every other resources to v3 right ? Or to remove them from the provider until they are migrated

**Comment by Cocossoul** [comment]
@sleungcy as I understand the situation, we cannot use the [official CLI v8 nor v7](https://github.com/cloudfoundry/cli) as is because the go module feature is not configured properly to be used as a library : https://github.com/cloudfoundry/cli/issues/2291

What we need to do it to update the [community fork](https://github.com/cloudfoundry-community/cloudfoundry-cli) to latest official branch and fix the go module so we can use it here.

I don't have any permissions on the community fork, could you do this please ?

**Comment by sleungcy** [comment]
In my opinion, we should get away from using the fork or even the cf-cli repo in this project. I have found multiple discrepancies from the cf-cli repo compared to the V3 API documentation. I have created multiple requests to the upstream project to address these discrepancies and all has been rejected:

The recommendation from the Cloudfoundry team for me was to convert to use go-cfclient

https://github.com/cloudfoundry/cli/pull/2881

Our fork of cf-cli also has diverged a whole lot and I’ve spent days to try re-converging the two and it’s quite a daunting task.

From my experiment, it was not a problem to consume both the cf-cli v3 api while also consuming the go-cfclient at the same time. We can continue to use the cf-cli v3 client for the things that exists today, and upgrade to go-cfclient for anything the old client does not provide. From what I can see, the go-cfclient is much much more aligned with the v3 api specifications.

**Comment by loafoe** [comment]
@sleungcy moving to `go-cfclient` is definitely the future proof step we should take yes. As for maintainership, since you have made the most significant changes in the past year I'm happy to bump your access if you are OK with it? :-)

**Comment by sleungcy** [comment]
Yes that would be great!

**Comment by loafoe** [comment]
> Yes that would be great!

Done!

**Pull request merged**
