### PR TITLE
fix service_instance resource failing to update synchronously

### PR DESCRIPTION
**Pull request by sleungcy**
Resolves an issue introduced in https://github.com/cloudfoundry-community/terraform-provider-cloudfoundry/pull/550

The service instance update api call can happen both synchronously and asynchronously, need to take into account that there is no jobURL returned when the request is done synchronously.

@Cocossoul Did your internal fork have this issue?

### CODE REVIEW

**Review by loafoe — APPROVED** [review]

**Comment by Cocossoul** [comment]
@sleungcy thanks for this fix

It did not happen with my internal fork, but we did not happen to do a service parameter update since my fix
I'll put your fix in our internal fork

**Comment by sleungcy** [comment]
@Cocossoul Have you ever had a need to actually update a service plan and the service parameters when the service broker does not support param upgrade with plan upgrade? What do you do to solve it in those case?

**Comment by Cocossoul** [comment]
@sleungcy I did not have this case yet, as we seldom update service plan.
However I sure thought about it when suggesting this fix, so my approach would be either to:

- do the plan upgrade with the cf cli (of course putting the right plan in TF config) and let Terraform do the service parameter update
- change the terraform provider so that it does multiple calls to the cf api, one for each attribute of the service instance resource that modified (possibly supporting partial state to keep track of the progress)

I'll probably go with the first, since it's still manageable at our scale, but surely it would be interesting to have the second functionnality in the provider

**Comment by sleungcy** [comment]
@Cocossoul 

Indeed the ordering will be a problem. I imagine that would be specific to the implementation of the service broker... For example if the new service plan does not support certain parameter value ranges that is being used with the current plan, but the current plan supports the parameter value supported by the new service plan, then the ordering would be to update the parameters first, then upgrade the service plan. It is the other way around if the new service plan supports the current service plan's parameters. But there will not be a clear winner if the parameter value range are mutually exclusive between the 2 service plans. 

The parameter specs of the service broker is unidentifiable through CF Api directly, we cannot determine through code the correct ordering other than re-trying every combinations.

**Pull request merged**
