### PR TITLE
Upgrade provider to use latest Terraform SDK v2.5.0

### PR DESCRIPTION
**Pull request by loafoe**
@ArthurHlt @psycofdj this would be the first set of PRs to move the provider to the latest release of the SDK. Next step would be to propagate the context variable.

### CODE REVIEW

**Comment by ArthurHlt** [comment]
Thanks @loafoe just could you clarify what is the context you are talking about ? Thanks for the jobs 👍

**Comment by loafoe** [comment]
@ArthurHlt currently the provider is still using the `v1` Terraform SDK. This patch moves to the `v2.2.0` SDK which is latest ([roadmap info is here](https://github.com/hashicorp/terraform-plugin-sdk/blob/master/ROADMAP.md)). It brings a lot of under the hoods changes namely switch to `terraform-plugin-mux` usage. Also it introduces context propagation and better error feedback to the main Terraform process. This requires more work to convert the calls, but this PR is required before we can start on that.

**Comment by loafoe** [comment]
@ArthurHlt one more reason to consider upgrading to latest SDK is that it supports local debugging of the provider which greatly speeds up development IMO.

**Comment by janosbinder** [comment]
@loafoe would this break the provider? If yes, what steps are needed to fix that?

**Comment by ArthurHlt** [comment]
@janosbinder it probably not breaking the provider but this remove the compatibility with terraform bellow 0.12. I will need also to run all test against this sdk version to ensure that it will not break anything.

I'm still here, just kinda busy on other subject and this part was delayed because some of users are still bellow 0.12 u=in my company. But sure the next release will include that

**Comment by loafoe** [comment]
@janosbinder indeed as @ArthurHlt mentioned the provider does not break, but will lose compatibility with older Terraform versions. We are running a version of the provider with the new SDK at my company for many months, no issues.

One other huge benefit of upgrading the SDK is that debugging the provider locally becomes much simpler i.e. you can start the provider binary in debug mode and attach terraform to it, so it supports breakpoint debugging, etc. etc.

**Comment by loafoe** [comment]
https://github.com/philips-labs/terraform-provider-cloudfoundry/blob/feature/local-debugging/main.go#L11-L29

**Comment by ArthurHlt** [comment]
@loafoe well I actually need to fix one thing on the provider (this one: instances coming in a random order cause a diff on new provider version) and release without the latest sdk only to start transitionning at my company. 

Right after the release I merge this and run acceptance test on it and fix issue if any

**Comment by loafoe** [comment]
Thanks @ArthurHlt , i will keep the branch up-to-date until you are ready to merge 👍🏻

**Pull request merged**
